unstable_features=true
chain_width=30
comment_width=0
condense_wildcard_suffixes=true
combine_control_expr=false
enum_discrim_align_threshold=40
fn_call_width=15
fn_single_line=true
format_code_in_doc_comments=true
format_macro_matchers=true
format_strings=true
hard_tabs=true
imports_granularity="One"
inline_attribute_width=60
match_arm_blocks=false
match_block_trailing_comma=true
reorder_impl_items=true
#space_around_ranges=true \\\ warned that unknown option
struct_field_align_threshold=40
#tab_spaces=3
trailing_comma="Always"
use_field_init_shorthand=true
use_small_heuristics="Max"
use_try_shorthand=true
where_single_line=true
wrap_comments=true
