unstable_features=true
max_width=130
condense_wildcard_suffixes=true
enum_discrim_align_threshold=40
fn_single_line=true
format_code_in_doc_comments=true
format_macro_matchers=true
format_strings=true
inline_attribute_width=50
match_arm_blocks=false
imports_granularity="One"
overflow_delimited_expr=true
reorder_impl_items=true
struct_field_align_threshold=40
tab_spaces=3
trailing_comma="Always"
use_field_init_shorthand=true
use_small_heuristics="Max"
where_single_line=true
wrap_comments=true
comments_width=130
